[veldmuis-core]
SigLevel = Required DatabaseOptional
Include = /etc/pacman.d/veldmuis-mirrorlist

[veldmuis-extra]
SigLevel = Required DatabaseOptional
Include = /etc/pacman.d/veldmuis-mirrorlist

# Enable later when you have a testing update flow.
#[veldmuis-testing]
#SigLevel = Required DatabaseOptional
#Include = /etc/pacman.d/veldmuis-mirrorlist
