[multilib]
Include = /etc/pacman.d/mirrorlist

[veldmuis-core]
SigLevel = Required DatabaseRequired
Include = /etc/pacman.d/veldmuis-mirrorlist

[veldmuis-extra]
SigLevel = Required DatabaseRequired
Include = /etc/pacman.d/veldmuis-mirrorlist
