# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
displaymanagers:
  - sddm

defaultDesktopEnvironment:
  executable: "/usr/bin/startplasma-wayland"
  desktopFile: "plasma"

basicSetup: false

sddm:
  configuration_file: "/etc/sddm.conf"
