# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
efi:
  mountPoint: "/boot/efi"
  recommendedSize: 300MiB
  minimumSize: 32MiB
  label: "EFI"

userSwapChoices:
  - none
  - small
  - suspend
  - file

luksGeneration: luks1
drawNestedPartitions: false
alwaysShowPartitionLabels: true
initialPartitioningChoice: none
initialSwapChoice: none

defaultFileSystemType: "ext4"
availableFileSystemTypes: [ "ext4", "btrfs", "xfs" ]
directoryFilesystemRestrictions:
  - directory: "any"
    allowedFilesystemTypes: [ "ext4", "btrfs", "xfs" ]
  - directory: "efi"
    allowedFilesystemTypes: [ "fat32" ]
    onlyWhenMountpoint: true

essentialMounts: [ "live-*", "control", "ventoy" ]

lvm:
  enable: true
