# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
units:
  - name: "NetworkManager.service"
    action: "enable"
    mandatory: true

  - name: "bluetooth.service"
    action: "enable"
    mandatory: false

  - name: "udisks2.service"
    action: "enable"
    mandatory: false

  - name: "systemd-timesyncd.service"
    action: "enable"
    mandatory: true

  - name: "power-profiles-daemon.service"
    action: "enable"
    mandatory: false

  - name: "sddm.service"
    action: "enable"
    mandatory: true

  - name: "spice-vdagentd.service"
    action: "enable"
    mandatory: false
