# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
units:
  - name: "NetworkManager.service"
    action: "enable"
    mandatory: true

  - name: "bluetooth.service"
    action: "enable"
    mandatory: false

  - name: "systemd-timesyncd.service"
    action: "enable"
    mandatory: true

  - name: "veldmuis-refresh-arch-mirrors.timer"
    action: "enable"
    mandatory: false

  - name: "power-profiles-daemon.service"
    action: "enable"
    mandatory: false

  - name: "plasmalogin.service"
    action: "enable"
    mandatory: true
