# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
units:
  - name: "NetworkManager.service"
    action: "enable"
    mandatory: true

  - name: "sddm.service"
    action: "enable"
    mandatory: true

  - name: "spice-vdagentd.service"
    action: "enable"
    mandatory: false
