# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
defaultGroups:
  - name: users
    must_exist: true
    system: true
  - lp
  - video
  - network
  - storage
  - name: wheel
    must_exist: false
    system: true
  - audio

sudoersGroup: wheel
autologinGroup: autologin
sudoersConfigureWithGroup: false

setRootPassword: false
doAutologin: false

passwordRequirements:
  minLength: -1
  maxLength: -1
  libpwquality:
    - minlen=0
    - minclass=0

allowWeakPasswords: true
allowWeakPasswordsDefault: true

user:
  shell: "/bin/bash"
