# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
dontChroot: true
timeout: 300
verbose: true

script:
  - command: "/usr/bin/arch-chroot \"${ROOT}\" /usr/lib/veldmuis/veldmuis-kernel-install-sync"
    timeout: 300
    verbose: true

i18n:
  name: "Finalize Veldmuis boot entries"
