# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
modules-search: [ local ]

instances:
  - id: veldmuis-bootstrap
    module: shellprocess
    config: veldmuis-bootstrap.conf
    weight: 40
  - id: veldmuis-boot-finalize
    module: shellprocess
    config: veldmuis-boot-finalize.conf
    weight: 42
  - id: graphics
    module: packagechooser
    config: graphics.conf
  - id: extras
    module: packagechooserq
    config: extras.conf

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - packagechooser@graphics
      - packagechooser@extras
      - users
      - summary
  - exec:
      - partition
      - mount
      - shellprocess@veldmuis-bootstrap
      - machineid
      - locale
      - keyboard
      - localecfg
      - fstab
      - initcpiocfg
      - initcpio
      - users
      - networkcfg
      - hwclock
      - services-systemd
      - bootloader
      - shellprocess@veldmuis-boot-finalize
      - umount
  - show:
      - finished

branding: veldmuis
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: true
hide-back-and-next-during-exec: false
quit-at-end: false
