[background]
path = "/usr/share/veldmuis/wallpapers/rat1.png"
fit = "Cover"

[GTK]
application_prefer_dark_theme = true
theme_name = "Breeze-Dark"
font_name = "Noto Sans 14"

[appearance]
greeting_msg = "Welcome to Veldmuis"

[commands]
reboot = [ "systemctl", "reboot" ]
poweroff = [ "systemctl", "poweroff" ]
