[General]
showlogo=hidden
showClock=true
logo=/usr/share/sddm/themes/veldmuis-breeze/default-logo.svg
type=image
color=#f0b030
fontSize=10
background=/usr/share/veldmuis/wallpapers/rat1.png
needsFullUserModel=false
