[Greeter]
PreselectedSession=plasma.desktop
ShowClock=true
WallpaperPluginId=org.kde.image

[Greeter][Wallpaper][org.kde.image][General]
FillMode=2
Image=file:///usr/share/wallpapers/VeldmuisDawn/contents/images/1920x1080.png
